import { MusicGenreTemplate, AssetLibraryItem, PostRenderFeedbackRecord } from '../types';

// ============================================================================
// 1. MÜZİK TÜRÜ & MOOD ŞABLONLARI (CURATED GENRE TEMPLATES)
// ============================================================================

export const MUSIC_GENRE_TEMPLATES: MusicGenreTemplate[] = [
  {
    id: 'tpl_studio_split_lyrics',
    name: 'Apple TV Split Lyrics Flow',
    genre: 'Spotify TV / Apple Music Canvas / Synced Lyrics / Indie / Pop / Rock',
    tagline: 'Sol tarafta track bilgileri & player, sağ tarafta akan şarkı sözleri',
    description: 'Sol tarafta 3D squircle albüm kapağı, FLAC audio rozeti, canlı scrubber ve çalma kontrolleri; sağ tarafta Apple Music / Spotify TV stili derinlik bulanıklığıyla pürüzsüz akan senkronize şarkı sözleri.',
    iconName: 'Sparkles',
    previewColors: ['#FFFFFF', '#38BDF8', '#818CF8'],
    fontFamily: 'display',
    badge: 'NEW',
    thumbnail: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=600&q=80',
    bgImageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1920&q=80',
    settings: {
      mode: 'STUDIO_SPLIT_LYRICS',
      aspectRatio: '16/9',
      primaryColor: '#FFFFFF',
      secondaryColor: '#38BDF8',
      bgMode: 'NONE',
      bgOpacity: 0.1,
      intensity: 1.1,
      bloomEnabled: true,
      bloom: 0.6,
      vignetteEnabled: true,
      vignette: 0.8,
      rgbSplitEnabled: false,
      filmGrainEnabled: true,
      filmGrain: 0.12,
      cameraShakeEnabled: false,
      cameraShake: 0.0,
      strobeEnabled: false,
      cardLayout: 'DEFAULT',
      lyricsStyle: 'BETTER_FLOW',
      lyricsPosition: 'CENTER',
      lyricsFontSize: 44,
      lyricsColor: '#FFFFFF',
      lyricsHighlightColor: '#FFFFFF',
      lyricsBlurInactive: true,
      lyricsShowVocalGapDots: true,
      lyricsLongNoteGlow: true
    }
  },
  {
    id: 'tpl_cover_pulse_3d',
    name: 'Cover Pulse 3D',
    genre: 'Spotify Single / Release Visual / Pop / Hip-Hop / Cyber',
    tagline: '3D albüm kapağı, yan EQ dalgaları ve Spotify/YouTube player',
    description: 'Kapak görselinin baskın rengiyle otomatik aydınlatılan 3D albüm objesi. Yanlardaki frekans EQ dalgaları, ıslak zemin yansıması ve şık müzik çalar arayüzü.',
    iconName: 'Flame',
    previewColors: ['#FF2A6D', '#05D9E8', '#FFD700'],
    fontFamily: 'display',
    badge: 'NEW',
    thumbnail: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=600&q=80',
    bgImageUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=1920&q=80',
    settings: {
      mode: 'COVER_PULSE_3D',
      aspectRatio: '16/9',
      primaryColor: '#FF2A6D',
      secondaryColor: '#05D9E8',
      bgMode: 'NONE',
      bgOpacity: 0.1,
      intensity: 1.25,
      bloomEnabled: true,
      bloom: 0.85,
      vignetteEnabled: true,
      vignette: 0.7,
      rgbSplitEnabled: false,
      filmGrainEnabled: true,
      filmGrain: 0.15,
      cameraShakeEnabled: true,
      cameraShake: 0.2,
      strobeEnabled: false,
      cardLayout: 'DEFAULT',
      lyricsStyle: 'SUBTITLE',
      lyricsPosition: 'BOTTOM',
      lyricsFontSize: 36,
      lyricsColor: '#FFFFFF'
    }
  },
  {
    id: 'tpl_rebellion',
    name: 'Rebellion',
    genre: 'Dark Phonk / Heavy Metal / Doom Beats',
    tagline: 'Derin karanlık duman, parlayan dairesel aura ve kırmızı tonlar',
    description: 'Agresif ve sarsıcı bas tonlarına uygun; koyu duman parçacıkları, kırmızı parlama, yoğun bloom efekti ve kinetik şarkı sözleri içeren agresif tasarım.',
    iconName: 'Flame',
    previewColors: ['#FF0F0F', '#000000', '#FF4D4D'],
    fontFamily: 'display',
    badge: 'NEW',
    thumbnail: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=600&q=80',
    bgImageUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1920&q=80',
    settings: {
      mode: 'CIRCULAR_AURA_SPECTRUM',
      aspectRatio: '16/9',
      primaryColor: '#FF003C',
      secondaryColor: '#000000',
      bgMode: 'SMOKE',
      bgOpacity: 0.15,
      intensity: 1.35,
      bloomEnabled: true,
      bloom: 0.9,
      vignetteEnabled: true,
      vignette: 0.75,
      rgbSplitEnabled: true,
      rgbSplit: 0.4,
      filmGrainEnabled: true,
      filmGrain: 0.3,
      cameraShakeEnabled: true,
      cameraShake: 0.35,
      strobeEnabled: true,
      strobe: 0.3,
      cardLayout: 'NEON_FRAME',
      lyricsStyle: 'CYBER_GLITCH',
      lyricsPosition: 'BOTTOM',
      lyricsFontSize: 44,
      lyricsColor: '#FF003C'
    }
  },
  {
    id: 'tpl_thru_space_time',
    name: 'thru space & time',
    genre: 'Space Techno / Psytrance / Progressive EDM',
    tagline: 'Sonsuz 3D siber tünel bükülmesi ve kozmik mavi/mor enerji',
    description: 'Kozmik hızda bir tünel yolculuğu. Yoğun parçacık akışı ve bas şok dalgaları ile ritmin derinliğini hissettirir.',
    iconName: 'Zap',
    previewColors: ['#00F0FF', '#BD00FF', '#FFE600'],
    fontFamily: 'display',
    badge: 'NEW',
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80',
    bgImageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1920&q=80',
    settings: {
      mode: 'NEON_TUNNEL',
      aspectRatio: '16/9',
      primaryColor: '#00F0FF',
      secondaryColor: '#BD00FF',
      bgMode: 'PARTICLES',
      bgOpacity: 0.12,
      intensity: 1.25,
      bloomEnabled: true,
      bloom: 0.85,
      vignetteEnabled: true,
      vignette: 0.6,
      rgbSplitEnabled: true,
      rgbSplit: 0.35,
      cameraShakeEnabled: true,
      cameraShake: 0.3,
      cardLayout: 'HOLO_CD',
      lyricsStyle: 'KINETIC',
      lyricsPosition: 'BOTTOM',
      lyricsFontSize: 40,
      lyricsColor: '#00F0FF'
    }
  },
  {
    id: 'tpl_digital_abyss',
    name: 'Digital Abyss',
    genre: 'Tech House / Minimal Techno / Cyberpunk',
    tagline: 'Kuantum parçacık küresi ve fütüristik grid HUD telemetrisi',
    description: 'Etkileşimli 3D parçacık küresi ve bas vuruşlarında genişleyen siber radar kılavuzları ile saf dijital estetik.',
    iconName: 'Sparkles',
    previewColors: ['#39FF14', '#FFA500', '#050B14'],
    fontFamily: 'mono',
    badge: 'NEW',
    thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&q=80',
    bgImageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1920&q=80',
    settings: {
      mode: 'PARTICLE_SPHERE_3D',
      aspectRatio: '16/9',
      primaryColor: '#39FF14',
      secondaryColor: '#FFA500',
      bgMode: 'GRID',
      bgOpacity: 0.1,
      intensity: 1.15,
      bloomEnabled: true,
      bloom: 0.75,
      scanLinesEnabled: true,
      scanLines: 0.25,
      filmGrainEnabled: false,
      cardLayout: 'DEFAULT',
      lyricsStyle: 'CYBER_GLITCH',
      lyricsPosition: 'CENTER',
      lyricsFontSize: 42,
      lyricsColor: '#39FF14'
    }
  },
  {
    id: 'tpl_forest_lights',
    name: 'Forest of Lights',
    genre: 'Cinematic Ambient / Indie / Chillout Acoustic',
    tagline: 'Mistik orman manzarası, süzülen ışık huzmeleri ve dikey EQ barları',
    description: 'Akustik gitarlar, piyano melodileri ve duygusal vokaller için dumanlı orman arka planı ve hassas logaritmik spektrum.',
    iconName: 'Music',
    previewColors: ['#E4E3E0', '#71717A', '#111827'],
    fontFamily: 'serif',
    badge: 'Pro',
    thumbnail: 'https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=600&q=80',
    bgImageUrl: 'https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=1920&q=80',
    settings: {
      mode: 'CAVA_SPECTRUM',
      aspectRatio: '16/9',
      primaryColor: '#FFFFFF',
      secondaryColor: '#A1A1AA',
      bgMode: 'NONE',
      bgOpacity: 0.05,
      intensity: 0.95,
      bloomEnabled: true,
      bloom: 0.4,
      vignetteEnabled: true,
      vignette: 0.55,
      filmGrainEnabled: true,
      filmGrain: 0.25,
      cardLayout: 'GLASS_CARD',
      lyricsStyle: 'SUBTITLE',
      lyricsPosition: 'BOTTOM',
      lyricsFontSize: 38,
      lyricsColor: '#FFFFFF'
    }
  },
  {
    id: 'tpl_prismatic_shard',
    name: 'Prismatic Shard',
    genre: 'Future Bass / Melodic Dubstep / Hyperpop',
    tagline: '3D kristal cam kırıkları ve dinamik renk kırılımları',
    description: 'Yarı saydam cam piramitler ve sese duyarlı geometrik spektrum halkaları ile can alıcı renk geçişleri.',
    iconName: 'Activity',
    previewColors: ['#FF007F', '#00F0FF', '#FFFFFF'],
    fontFamily: 'display',
    badge: 'Pro',
    thumbnail: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=600&q=80',
    bgImageUrl: 'https://images.unsplash.com/photo-1634017839464-5c339ebe3cb4?auto=format&fit=crop&w=1920&q=80',
    settings: {
      mode: 'VISSONANCE_RING',
      aspectRatio: '16/9',
      primaryColor: '#FF007F',
      secondaryColor: '#00F0FF',
      bgMode: 'SMOKE',
      bgOpacity: 0.08,
      intensity: 1.25,
      bloomEnabled: true,
      bloom: 0.85,
      lensDistortEnabled: true,
      lensDistort: 0.25,
      cardLayout: 'DEFAULT',
      lyricsStyle: 'NEON_BOX',
      lyricsPosition: 'CENTER',
      lyricsFontSize: 44,
      lyricsColor: '#FFFFFF'
    }
  },
  {
    id: 'tpl_infrared',
    name: 'Infrared',
    genre: 'Synthwave / Outrun / Retro 80s',
    tagline: 'Sonsuz retro 3D perspektif grid, dağ zirvesi ve neon güneş',
    description: 'Sıcak 80ler kaset greni, RGB kayması, yatay scanline çizgileri ve sese duyarlı sonsuz ufuk çizgisi.',
    iconName: 'Sliders',
    previewColors: ['#FF00FF', '#00FFFF', '#FF9F00'],
    fontFamily: 'display',
    badge: 'Pro',
    thumbnail: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=600&q=80',
    bgImageUrl: 'https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=1920&q=80',
    settings: {
      mode: 'SYNTHWAVE_GRID_3D',
      aspectRatio: '16/9',
      primaryColor: '#FF007F',
      secondaryColor: '#00FFFF',
      bgMode: 'GRID',
      bgOpacity: 0.15,
      intensity: 1.15,
      bloomEnabled: true,
      bloom: 0.8,
      scanLinesEnabled: true,
      scanLines: 0.4,
      rgbSplitEnabled: true,
      rgbSplit: 0.35,
      filmGrainEnabled: true,
      filmGrain: 0.2,
      cardLayout: 'RETRO_TAPE',
      lyricsStyle: 'CYBER_GLITCH',
      lyricsPosition: 'BOTTOM',
      lyricsFontSize: 42,
      lyricsColor: '#00FFFF'
    }
  },
  {
    id: 'tpl_jungle_cat',
    name: 'Jungle Cat',
    genre: 'Afro Beats / Deep House / Organic Lounge',
    tagline: 'Karanlık vahşi orman aslanı portresi ve pürüzsüz spektrum barları',
    description: 'Şık ve vahşi bir atmosfer. Güçlü orta-bas frekans vuruşlarında parıldayan logaritmik EQ tasarımı.',
    iconName: 'Flame',
    previewColors: ['#FFD700', '#27272A', '#18181B'],
    fontFamily: 'sans',
    badge: null,
    thumbnail: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?auto=format&fit=crop&w=600&q=80',
    bgImageUrl: 'https://images.unsplash.com/photo-1546182990-dffeafbe841d?auto=format&fit=crop&w=1920&q=80',
    settings: {
      mode: 'SPECTRUM',
      aspectRatio: '16/9',
      primaryColor: '#FFD700',
      secondaryColor: '#E4E3E0',
      bgMode: 'NONE',
      bgOpacity: 0.05,
      intensity: 1.0,
      bloomEnabled: true,
      bloom: 0.5,
      vignetteEnabled: true,
      vignette: 0.65,
      cardLayout: 'COVER_BIG',
      lyricsStyle: 'SUBTITLE',
      lyricsPosition: 'BOTTOM',
      lyricsFontSize: 40,
      lyricsColor: '#FFD700'
    }
  },
  {
    id: 'tpl_default_brutal',
    name: 'Default',
    genre: 'Minimal Techno / Industrial / Dark Ambient',
    tagline: 'Siyah monolit sütunlar, brutalist 3D perspektif ve saf gri tonları',
    description: 'Monoton, endüstriyel ve şık. Siyah beyaz perspektif çizgileri ve bas vuruşlarında sarsılan kamera sarsıntısı.',
    iconName: 'Activity',
    previewColors: ['#FFFFFF', '#71717A', '#09090B'],
    fontFamily: 'mono',
    badge: null,
    thumbnail: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=600&q=80',
    bgImageUrl: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?auto=format&fit=crop&w=1920&q=80',
    settings: {
      mode: 'MONOLITH',
      aspectRatio: '16/9',
      primaryColor: '#FFFFFF',
      secondaryColor: '#71717A',
      bgMode: 'NONE',
      bgOpacity: 0.0,
      intensity: 1.2,
      filmGrainEnabled: true,
      filmGrain: 0.35,
      cameraShakeEnabled: true,
      cameraShake: 0.25,
      cardLayout: 'NOIR_VINYL',
      lyricsStyle: 'SUBTITLE',
      lyricsPosition: 'BOTTOM',
      lyricsFontSize: 38,
      lyricsColor: '#E4E3E0'
    }
  },
  {
    id: 'tpl_magma_molten',
    name: 'Magma',
    genre: 'Doom Phonk / Hardcore Trap / Dark Phonk',
    tagline: 'Erimiş magma akışkanları ve parıldayan kırmızı şok dalgaları',
    description: 'Yeraltı siberpunk magma akıntıları. Distortion cowbell ritimlerini sarsıntılı bas aurasıyla besleyen tasarım.',
    iconName: 'Flame',
    previewColors: ['#FF2200', '#1A0500', '#FFAA00'],
    fontFamily: 'display',
    badge: null,
    thumbnail: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=600&q=80',
    bgImageUrl: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?auto=format&fit=crop&w=1920&q=80',
    settings: {
      mode: 'CIRCULAR_AURA_SPECTRUM',
      aspectRatio: '16/9',
      primaryColor: '#FF2200',
      secondaryColor: '#FFAA00',
      bgMode: 'SMOKE',
      bgOpacity: 0.12,
      intensity: 1.3,
      bloomEnabled: true,
      bloom: 0.8,
      strobeEnabled: true,
      strobe: 0.35,
      cardLayout: 'NEON_FRAME',
      lyricsStyle: 'CYBER_GLITCH',
      lyricsPosition: 'CENTER',
      lyricsFontSize: 46,
      lyricsColor: '#FF2200'
    }
  },
  {
    id: 'tpl_coil_sky',
    name: 'Coil',
    genre: 'Deep Tech / Melodic Techno / progressive',
    tagline: 'Gece şehri yansıması ve dairesel polar frekans halkaları',
    description: 'Metropol silüeti üzerinde basla bükülen dairesel polar osiloskop halkaları ve genişleyen dikey ışık barları.',
    iconName: 'Zap',
    previewColors: ['#0088FF', '#A3E635', '#090D16'],
    fontFamily: 'sans',
    badge: null,
    thumbnail: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=600&q=80',
    bgImageUrl: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?auto=format&fit=crop&w=1920&q=80',
    settings: {
      mode: 'CODROPS_POLAR',
      aspectRatio: '16/9',
      primaryColor: '#0088FF',
      secondaryColor: '#A3E635',
      bgMode: 'GRID',
      bgOpacity: 0.1,
      intensity: 1.15,
      bloomEnabled: true,
      bloom: 0.75,
      vignetteEnabled: true,
      vignette: 0.5,
      cardLayout: 'HOLO_CD',
      lyricsStyle: 'KINETIC',
      lyricsPosition: 'BOTTOM',
      lyricsFontSize: 42,
      lyricsColor: '#0088FF'
    }
  },
  {
    id: 'tpl_skyline_mono',
    name: 'Skyline',
    genre: 'Lo-Fi Jazz / Chillhop / Retro Beats',
    tagline: 'Siyah beyaz gökdelen perspektifi ve logaritmik stüdyo barları',
    description: 'Nostaljik daktilo şarkı sözleri, kaset çıtırtı efekti, yüksek kumlanma ve sade, dairesel olmayan spektrum.',
    iconName: 'Music',
    previewColors: ['#E4E3E0', '#1C1917', '#78716C'],
    fontFamily: 'serif',
    badge: null,
    thumbnail: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=600&q=80',
    bgImageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1920&q=80',
    settings: {
      mode: 'SPECTRUM',
      aspectRatio: '16/9',
      primaryColor: '#FFFFFF',
      secondaryColor: '#78716C',
      bgMode: 'NONE',
      bgOpacity: 0.05,
      intensity: 0.9,
      filmGrainEnabled: true,
      filmGrain: 0.5,
      vignetteEnabled: true,
      vignette: 0.5,
      cardLayout: 'GLASS_CARD',
      lyricsStyle: 'SUBTITLE',
      lyricsPosition: 'BOTTOM',
      lyricsFontSize: 38,
      lyricsColor: '#FFFFFF'
    }
  },
  {
    id: 'tpl_red_planet',
    name: 'Red Planet',
    genre: 'Progressive Trance / Ambient / Psychedelic',
    tagline: 'Kızıl Mars yüzeyi ve çift kanallı osiloskop ses dalgası',
    description: 'Uzay tozları ve volkanik arazi dokusu üzerinde parıldayan osiloskop çizgileri ve bas şok dalgaları.',
    iconName: 'Zap',
    previewColors: ['#FF3333', '#110303', '#FF6666'],
    fontFamily: 'mono',
    badge: null,
    thumbnail: 'https://images.unsplash.com/photo-1612892483236-42d68a57623d?auto=format&fit=crop&w=600&q=80',
    bgImageUrl: 'https://images.unsplash.com/photo-1612892483236-42d68a57623d?auto=format&fit=crop&w=1920&q=80',
    settings: {
      mode: 'CODROPS_WAVE',
      aspectRatio: '16/9',
      primaryColor: '#FF3333',
      secondaryColor: '#FF6666',
      bgMode: 'PARTICLES',
      bgOpacity: 0.08,
      intensity: 1.2,
      bloomEnabled: true,
      bloom: 0.75,
      strobeEnabled: true,
      strobe: 0.25,
      cardLayout: 'DEFAULT',
      lyricsStyle: 'KARAOKE',
      lyricsPosition: 'BOTTOM',
      lyricsFontSize: 40,
      lyricsColor: '#FF3333'
    }
  },
  {
    id: 'tpl_cyber_drift',
    name: 'Cyber Drifting',
    genre: 'Drift Phonk / Hard Bass / Cyberpunk',
    tagline: 'Sonsuz neon yeşili siber matrix tüneli',
    description: 'Hızlı drift ritimleri ve ağır 808 cowbell vuruşları için ideal neon yeşili ve siberpunk tünel simülasyonu.',
    iconName: 'Flame',
    previewColors: ['#39FF14', '#000000', '#00FFFF'],
    fontFamily: 'display',
    badge: 'NEW',
    thumbnail: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=600&q=80',
    bgImageUrl: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?auto=format&fit=crop&w=1920&q=80',
    settings: {
      mode: 'NEON_TUNNEL',
      aspectRatio: '16/9',
      primaryColor: '#39FF14',
      secondaryColor: '#00FFFF',
      bgMode: 'GRID',
      bgOpacity: 0.15,
      intensity: 1.4,
      bloomEnabled: true,
      bloom: 0.95,
      rgbSplitEnabled: true,
      rgbSplit: 0.45,
      cameraShakeEnabled: true,
      cameraShake: 0.4,
      scanLinesEnabled: true,
      scanLines: 0.3,
      cardLayout: 'NEON_FRAME',
      lyricsStyle: 'CYBER_GLITCH',
      lyricsPosition: 'BOTTOM',
      lyricsFontSize: 42,
      lyricsColor: '#39FF14'
    }
  },
  {
    id: 'tpl_acid_flashback',
    name: 'Acid Flashback',
    genre: 'Acid Techno / Psytrance / Industrial',
    tagline: 'Göz alıcı strobe flaşörleri ve reaktif dairesel osiloskop',
    description: 'Asit bas hatları ve yüksek BPM davulları için parıldayan yeşil-mor polar çemberler ve yoğun strobe efektleri.',
    iconName: 'Zap',
    previewColors: ['#39FF14', '#BD00FF', '#000000'],
    fontFamily: 'mono',
    badge: 'NEW',
    thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&q=80',
    bgImageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1920&q=80',
    settings: {
      mode: 'CODROPS_POLAR',
      aspectRatio: '16/9',
      primaryColor: '#39FF14',
      secondaryColor: '#BD00FF',
      bgMode: 'PARTICLES',
      bgOpacity: 0.18,
      intensity: 1.3,
      bloomEnabled: true,
      bloom: 0.85,
      strobeEnabled: true,
      strobe: 0.45,
      cameraShakeEnabled: true,
      cameraShake: 0.35,
      cardLayout: 'HOLO_CD',
      lyricsStyle: 'CYBER_GLITCH',
      lyricsPosition: 'BOTTOM',
      lyricsFontSize: 40,
      lyricsColor: '#39FF14'
    }
  },
  {
    id: 'tpl_vapor_sunset',
    name: 'Vaporwave Sunset',
    genre: 'Vaporwave / Chillwave / Synthwave',
    tagline: 'Yatay neon scanline çizgileri ve vintage kaset',
    description: '80ler nostaljisini canlandıran pembe/mavi neon dağ ızgarası, CRT scanline çizgileri ve kaset gren filtresi.',
    iconName: 'Sliders',
    previewColors: ['#FF00FF', '#00FFFF', '#FFA500'],
    fontFamily: 'display',
    badge: 'Pro',
    thumbnail: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=600&q=80',
    bgImageUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=1920&q=80',
    settings: {
      mode: 'SYNTHWAVE_GRID_3D',
      aspectRatio: '16/9',
      primaryColor: '#FF00FF',
      secondaryColor: '#00FFFF',
      bgMode: 'GRID',
      bgOpacity: 0.2,
      intensity: 1.1,
      bloomEnabled: true,
      bloom: 0.75,
      scanLinesEnabled: true,
      scanLines: 0.4,
      filmGrainEnabled: true,
      filmGrain: 0.3,
      cardLayout: 'RETRO_TAPE',
      lyricsStyle: 'KINETIC',
      lyricsPosition: 'BOTTOM',
      lyricsFontSize: 44,
      lyricsColor: '#FF00FF'
    }
  },
  {
    id: 'tpl_cosmic_dream',
    name: 'Cosmic Dream',
    genre: 'Space Ambient / Chillout / Cinematic',
    tagline: 'Sonsuz kozmik rüya parçacıkları ve parıldayan dairesel halka',
    description: 'Derin kozmik yolculuklar için süzülen mor-mavi parçacık küresi, logaritmik genişleme ve yumuşak sis.',
    iconName: 'Music',
    previewColors: ['#BD00FF', '#00F0FF', '#FFFFFF'],
    fontFamily: 'serif',
    badge: 'Pro',
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80',
    bgImageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1920&q=80',
    settings: {
      mode: 'QUANTUM_FIELD',
      aspectRatio: '16/9',
      primaryColor: '#BD00FF',
      secondaryColor: '#00F0FF',
      bgMode: 'PARTICLES',
      bgOpacity: 0.12,
      intensity: 0.95,
      bloomEnabled: true,
      bloom: 0.8,
      vignetteEnabled: true,
      vignette: 0.6,
      cardLayout: 'GLASS_CARD',
      lyricsStyle: 'SUBTITLE',
      lyricsPosition: 'BOTTOM',
      lyricsFontSize: 38,
      lyricsColor: '#FFFFFF'
    }
  },
  {
    id: 'tpl_acoustic_solitude',
    name: 'Acoustic Solitude',
    genre: 'Indie Folk / Lo-Fi Acoustic / Piano Lounge',
    tagline: 'Mistik dumanlı orman ve pürüzsüz dikey equalizer barları',
    description: 'Akustik gitarlar, sakin vokal kayıtları ve piyano parçaları için mistik orman arka planlı klasik dikey spektrum barları.',
    iconName: 'Music',
    previewColors: ['#E4E3E0', '#71717A', '#09090B'],
    fontFamily: 'serif',
    badge: null,
    thumbnail: 'https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=600&q=80',
    bgImageUrl: 'https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=1920&q=80',
    settings: {
      mode: 'SPECTRUM',
      aspectRatio: '16/9',
      primaryColor: '#FFFFFF',
      secondaryColor: '#A1A1AA',
      bgMode: 'NONE',
      bgOpacity: 0.05,
      intensity: 0.85,
      filmGrainEnabled: true,
      filmGrain: 0.2,
      vignetteEnabled: true,
      vignette: 0.5,
      cardLayout: 'GLASS_CARD',
      lyricsStyle: 'SUBTITLE',
      lyricsPosition: 'BOTTOM',
      lyricsFontSize: 36,
      lyricsColor: '#E4E3E0'
    }
  },
  {
    id: 'tpl_cyberpunk_hud',
    name: 'Cyberpunk HUD',
    genre: 'Industrial Techno / Cyberpunk EDM',
    tagline: 'Siberpunk radar gridi ve sese duyarlı telemetry halkası',
    description: 'Gelecek temalı siber matrix dalgası, 3D radar ızgarası, anlık dalgalı frekans halkaları ve yeşil neonlar.',
    iconName: 'Sparkles',
    previewColors: ['#39FF14', '#000000', '#FF003C'],
    fontFamily: 'mono',
    badge: 'NEW',
    thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=600&q=80',
    bgImageUrl: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1920&q=80',
    settings: {
      mode: 'SIMULATION',
      aspectRatio: '16/9',
      primaryColor: '#39FF14',
      secondaryColor: '#FF003C',
      bgMode: 'GRID',
      bgOpacity: 0.15,
      intensity: 1.25,
      bloomEnabled: true,
      bloom: 0.8,
      scanLinesEnabled: true,
      scanLines: 0.35,
      cardLayout: 'DEFAULT',
      lyricsStyle: 'CYBER_GLITCH',
      lyricsPosition: 'CENTER',
      lyricsFontSize: 42,
      lyricsColor: '#39FF14'
    }
  },
  {
    id: 'tpl_spotify_player',
    name: 'Spotify Pro Player',
    genre: 'Lofi HipHop / Chill / Playlist',
    tagline: 'Gerçekçi Spotify albüm çalar arayüzü ve dalgalı aura spektrumu',
    description: 'Sanki doğrudan bir müzik çalar gibi görünen albüm kapaklı, parça ilerleme çubuklu ve Spotify aura halkalı stüdyo oynatıcı tasarımı.',
    iconName: 'Music',
    previewColors: ['#1DB954', '#191414', '#FFFFFF'],
    fontFamily: 'sans',
    badge: 'Pro',
    thumbnail: 'https://images.unsplash.com/photo-1614680376593-902f74fa0d41?auto=format&fit=crop&w=600&q=80',
    bgImageUrl: 'https://images.unsplash.com/photo-1614680376593-902f74fa0d41?auto=format&fit=crop&w=1920&q=80',
    settings: {
      mode: 'CIRCULAR_AURA_SPECTRUM',
      aspectRatio: '16/9',
      primaryColor: '#1DB954',
      secondaryColor: '#191414',
      bgMode: 'NONE',
      bgOpacity: 0.1,
      intensity: 1.1,
      bloomEnabled: true,
      bloom: 0.7,
      cardLayout: 'SPOTIFY',
      lyricsStyle: 'SUBTITLE',
      lyricsPosition: 'BOTTOM',
      lyricsFontSize: 38,
      lyricsColor: '#1DB954'
    }
  },
  {
    id: 'tpl_vrm_avatar',
    name: '3D VRM Anime Avatar',
    genre: 'V-Tuber / Electronic / J-Pop',
    tagline: '3D VRM Anime karakteriyle canlı lip-sync performansı',
    description: 'Gelişmiş 3D VRM modelleyici, dudak hareketleri (Lip sync), sese duyarlı yüz ışıklandırması ve göz kırpma döngüsü.',
    iconName: 'User',
    previewColors: ['#FF007F', '#000000', '#00FFFF'],
    fontFamily: 'sans',
    badge: 'NEW',
    thumbnail: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=600&q=80',
    bgImageUrl: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=1920&q=80',
    settings: {
      mode: 'VRM_ANIME_HYBRID',
      aspectRatio: '16/9',
      primaryColor: '#FF007F',
      secondaryColor: '#00FFFF',
      bgMode: 'PARTICLES',
      bgOpacity: 0.15,
      intensity: 1.2,
      bloomEnabled: true,
      bloom: 0.8,
      vrmModelUrl: '/models/AliciaSolid.vrm',
      vrmModelName: 'Alicia Solid',
      cardLayout: 'DEFAULT',
      lyricsStyle: 'CYBER_GLITCH',
      lyricsPosition: 'BOTTOM',
      lyricsFontSize: 40,
      lyricsColor: '#FF007F'
    }
  }
];

// ============================================================================
// 2. ASSET KÜTÜPHANESİ KATALOĞU (ASSET LIBRARY)
// ============================================================================

export const ASSET_LIBRARY_ITEMS: AssetLibraryItem[] = [
  // --- ARKAPLANLAR (BACKGROUNDS) ---
  {
    id: 'asset_bg_neon_city',
    name: 'Neon Cyber City 2077',
    category: 'BACKGROUND',
    thumbnail: 'https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=300&h=200&fit=crop',
    description: 'Yüksek binalar, neon ışık yansımaları ve derin cyberpunk atmosferi.',
    badge: '4K DÖNGÜ',
    applyConfig: {
      bgMode: 'GRID',
      bgOpacity: 0.12,
      primaryColor: '#00F0FF',
      secondaryColor: '#FF007F'
    }
  },
  {
    id: 'asset_bg_smoke_haze',
    name: 'Cinematic Smoke & Fog',
    category: 'BACKGROUND',
    thumbnail: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=300&h=200&fit=crop',
    description: 'Konser ve stüdyo havası veren sese duyarlı yumuşak duman sisi.',
    badge: 'SESE DUYARLI',
    applyConfig: {
      bgMode: 'PARTICLES',
      bgOpacity: 0.08,
      filmGrainEnabled: true,
      filmGrain: 0.25
    }
  },
  {
    id: 'asset_bg_deep_particles',
    name: 'Quantum Audio Particles',
    category: 'BACKGROUND',
    thumbnail: 'https://images.unsplash.com/photo-1506703719100-a0f3a48c0f86?w=300&h=200&fit=crop',
    description: 'Bas vuruşlarında etrafa saçılan 2000+ mikro ışık parçacığı.',
    badge: 'POPÜLER',
    applyConfig: {
      bgMode: 'PARTICLES',
      bgOpacity: 0.1,
      edgeGlowEnabled: true,
      edgeGlow: 0.7
    }
  },
  {
    id: 'asset_bg_stars_cosmos',
    name: 'Cosmic Nebula & Stars',
    category: 'BACKGROUND',
    thumbnail: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=300&h=200&fit=crop',
    description: 'Sonsuz uzay derinliği, dönen yıldız tozları ve galaktik renkler.',
    badge: '60 FPS',
    applyConfig: {
      bgMode: 'PARTICLES',
      bgOpacity: 0.06,
      bloomEnabled: true,
      bloom: 0.8
    }
  },
  {
    id: 'asset_bg_cyber_grid_3d',
    name: 'Tron Retro Cyber Grid',
    category: 'BACKGROUND',
    thumbnail: 'https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=300&h=200&fit=crop',
    description: 'Sonsuza uzanan 3D perspektif zemin çizgileri ve bas dalgaları.',
    badge: 'SYNTHWAVE',
    applyConfig: {
      bgMode: 'GRID',
      bgOpacity: 0.14,
      scanLinesEnabled: true,
      scanLines: 0.3
    }
  },

  // --- OVERLAYLER (OVERLAYS) ---
  {
    id: 'asset_ov_vhs_tape',
    name: 'VHS Camcorder 1989',
    category: 'OVERLAY',
    thumbnail: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=300&h=200&fit=crop',
    description: 'Tarih sayacı, SP kayıt modu, tracking hatası ve analog kaset paraziti.',
    badge: 'RETRO',
    applyConfig: {
      rgbSplitEnabled: true,
      rgbSplit: 0.4,
      scanLinesEnabled: true,
      scanLines: 0.35,
      filmGrainEnabled: true,
      filmGrain: 0.3
    }
  },
  {
    id: 'asset_ov_crt_scanlines',
    name: 'CRT Phosphor Scanlines',
    category: 'OVERLAY',
    thumbnail: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=300&h=200&fit=crop',
    description: 'Tüplü televizyon fosfor çizgileri ve köşelerde kavisli cam efekti.',
    badge: 'ANALOG',
    applyConfig: {
      scanLinesEnabled: true,
      scanLines: 0.45,
      vignetteEnabled: true,
      vignette: 0.6
    }
  },
  {
    id: 'asset_ov_film_grain_35mm',
    name: '35mm Kodak Film Grain',
    category: 'OVERLAY',
    thumbnail: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=300&h=200&fit=crop',
    description: 'Sinematik sıcaklık katan gerçekçi gümüş halojenür film kumlanması.',
    badge: 'SİNEMATİK',
    applyConfig: {
      filmGrainEnabled: true,
      filmGrain: 0.5,
      bloomEnabled: true,
      bloom: 0.45
    }
  },
  {
    id: 'asset_ov_noise_dust',
    name: 'Analog Dust & Noise Texture',
    category: 'OVERLAY',
    thumbnail: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=300&h=200&fit=crop',
    description: 'Lo-Fi ve vintage parçalarda plak çıtırtısı hissini görselleştiren toz dokusu.',
    badge: 'LO-FI',
    applyConfig: {
      filmGrainEnabled: true,
      filmGrain: 0.4,
      vignetteEnabled: true,
      vignette: 0.5
    }
  },
  {
    id: 'asset_ov_glitch_chroma',
    name: 'RGB Glitch Slice Surge',
    category: 'OVERLAY',
    thumbnail: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=300&h=200&fit=crop',
    description: 'Bas transient vuruşlarında tetiklenen kromatik kayma ve veri dilimleme.',
    badge: 'PHONK/TRAP',
    applyConfig: {
      rgbSplitEnabled: true,
      rgbSplit: 0.55,
      strobeEnabled: true,
      strobe: 0.35,
      cameraShakeEnabled: true,
      cameraShake: 0.3
    }
  },

  // --- GEOMETRİK KATMANLAR (GEOMETRIC LAYERS) ---
  {
    id: 'asset_geo_tunnel_warp',
    name: 'Hyperdrive Warp Tunnel',
    category: 'GEOMETRIC_LAYER',
    thumbnail: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=300&h=200&fit=crop',
    description: 'Müziğin ritmiyle iç içe geçen ve derinlik hissi veren sonsuz tünel halkaları.',
    badge: '3D DEEP',
    applyConfig: {
      visScale: 1.2,
      visSpeed: 1.3,
      visGlow: 0.85
    }
  },
  {
    id: 'asset_geo_sacred_circle',
    name: 'Sacred Audio Geometry Ring',
    category: 'GEOMETRIC_LAYER',
    thumbnail: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=300&h=200&fit=crop',
    description: 'Altın oran çemberleri ve 360 derece sese duyarlı frekans yayları.',
    badge: 'MİNİMAL',
    applyConfig: {
      visDensity: 1.25,
      visRotation: 0.8,
      visBeatSensitivity: 1.2
    }
  },
  {
    id: 'asset_geo_pulse_triangle',
    name: 'Cyber Wireframe Triangle',
    category: 'GEOMETRIC_LAYER',
    thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=300&h=200&fit=crop',
    description: 'Karanlık tekno ve synthwave için dönen ve basla nefes alan neon üçgen.',
    badge: 'CYBER',
    applyConfig: {
      visScale: 1.1,
      visGlow: 0.9,
      edgeGlowEnabled: true,
      edgeGlow: 0.8
    }
  }
];

// ============================================================================
// 3. FAZ 2 KALICI GERİ BİLDİRİM DEPOLAMA YARDIMCISI (FEEDBACK UTILS)
// ============================================================================

const FEEDBACK_STORAGE_KEY = 'vidframer_post_render_feedback_v2';

export function getSavedFeedback(): PostRenderFeedbackRecord[] {
  try {
    const raw = localStorage.getItem(FEEDBACK_STORAGE_KEY);
    if (!raw) return [];
    return JSON.parse(raw);
  } catch (e) {
    console.warn('Feedback get error:', e);
    return [];
  }
}

export function savePostRenderFeedback(record: PostRenderFeedbackRecord) {
  try {
    const existing = getSavedFeedback();
    const updated = [record, ...existing].slice(0, 200); // keep last 200
    localStorage.setItem(FEEDBACK_STORAGE_KEY, JSON.stringify(updated));
  } catch (e) {
    console.warn('Feedback save error:', e);
  }
}
